//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ticketingSystem_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public int Project { get; set; }
        public Nullable<int> Assignee { get; set; }
        public int Status { get; set; }
        public Nullable<int> Priorty { get; set; }
        public int Id { get; set; }
    }
}
